### ISSUE TITLE
devbox run update error

### ISSUE THREAD

**Issue by ineiti** [c4dt/rse.epfl.ch#8]
@elanti has an error when using `devbox run update`. Here is my `rclone.conf`:

```
% cat ~/.config/rclone/rclone.conf 
[ic-ftps]
type = ftp
host = ic-ftps.epfl.ch
pass = somethingsomething
tls = false
explicit_tls = true
```

**Comment by elanti** [comment]
For reference, mine is the same, except for the order of the options :)
```
> cat ~/.config/rclone/rclone.conf 
[ic-ftps]
type = ftp
host = ic-ftps.epfl.ch
tls = false
explicit_tls = true
pass = something
```
Tried, with Linus', but it doesn't work. I will continue investigating.

**Comment by ineiti** [comment]
1. Are you in EPFL's network, either physically or using a VPN?
2. What is the error message you get?

**Comment by elanti** [comment]
I am using the VPN, but I will try tomorrow at EPFL. I am not sure it is a connection problem. I can ping the machine.

When running the update, I have:
```
> devbox run update
Info: Ensuring packages are installed.
✓ Computed the Devbox environment.
Already up to date.
Start building sites … 
hugo v0.126.1+extended linux/amd64 BuildDate=unknown VendorInfo=nixpkgs


                   | EN  
-------------------+-----
  Pages            | 15  
  Paginator pages  |  0  
  Non-page files   |  3  
  Static files     |  1  
  Processed images |  0  
  Aliases          |  1  
  Cleaned          |  0  

Total in 142 ms
2024/05/22 16:46:08 ERROR : 404.html: Failed to copy: update stor: 550 /rse.epfl.ch/404.html.xunuqiw2.partial: No such file or directory
2024/05/22 16:46:09 ERROR : index.xml: Failed to copy: update stor: 550 /rse.epfl.ch/index.xml.zitogon5.partial: No such file or directory
2024/05/22 16:46:09 ERROR : index.html: Failed to copy: update stor: 550 /rse.epfl.ch/index.html.yovoduk2.partial: No such file or directory
2024/05/22 16:46:09 ERROR : sitemap.xml: Failed to copy: update stor: 550 /rse.epfl.ch/sitemap.xml.xegojin3.partial: No such file or directory
[...]
```
and the list goes on with basically every file.

**Comment by ineiti** [comment]
Here it works over VPN, so it cannot be that.

According to [this](https://forum.rclone.org/t/no-such-file-or-directory-from-mac-to-ftp-nas) it could be the version of rclone. Can you try to:

```bash
devbox add rclone@1.64.2
devbox run update
```

?

**Comment by ineiti** [comment]
I pushed the 1.64.2 version to `main`. You can do a git pull and try out if that works.

**Comment by ineiti** [comment]
Another idea: perhaps it's a permission problem. Can you try to connect to the server by other means and check if you can create new files and modify existing ones?

**Comment by elanti** [comment]
Thanks a lot for investigating this !

I updated `rclone` (by mistake) and got version 1.66.9. It is still not working. 

I tried connecting on the machine using ssh, but I got a connection closed:
```
> ssh ic-ftps.epfl.ch
lanti@ic-ftps.epfl.ch's password: 
Connection closed by 10.95.48.54 port 22
```

**Comment by ineiti** [comment]
It's not sftp, but ftps. So not ftp-over-ssh, but ftp-over-tls. It's a mess, I have no idea why they choose this format. Even rclone needs special care to actually be able to use it.

On Mac I use Cyberduck, I don't know which program under Linux talks ftps.

Perhaps if you try to copy any file (something.txt) over and see if that works? If that fails, then I can open a ticket with support-icit and ask them to fix it.

**Comment by elanti** [comment]
Oups sorry, I totally missed that...

I just tried using Fillezilla to connect and it works, but I can only see `/` and there is nothing in there. After trying to transfer a file I get this output:
```
Status:	Resolving address of ic-ftps.epfl.ch
Status:	Connecting to 10.95.48.54:21...
Status:	Connection established, waiting for welcome message...
Status:	Initializing TLS...
Status:	TLS connection established.
Status:	Logged in
Status:	Starting upload of /tmp/test
Command:	CWD /
Response:	250 CWD command successful
Command:	PWD
Response:	257 "/" is the current directory
Command:	TYPE A
Response:	200 Type set to A
Command:	PASV
Response:	227 Entering Passive Mode (10,95,48,54,172,147).
Command:	STOR test
Response:	550 test: Permission denied
Error:	Critical file transfer error
```
So it seems to be indeed a permission problem.

**Comment by ineiti** [comment]
The issue was an error in one of the scripts which set up the permissions, so not the rclone version.
